spring.application.name=user-service

server.port=8080

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://db-user:3306/user_db
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CONEXIONES
# IMPORTANTE: usar el container_name + puerto INTERNO del contenedor destino
auth.service.url=http://Auth-service:8089

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar SpringDoc y Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html