spring.application.name=logistic_service

server.port=8086

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://db-logistic:3306/logistic_db
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# En el servicio Comms (corriendo en EC2-B), llamando al servicio Orden (en EC2-A) y servicio User (corriendo en EC2-B)
orden.service.url=${ORDEN_URL:http://localhost:8084}

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true